name: Publish to PyPI
on:
  release:
    types: [published]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    
    - name: Clean previous builds
      run: |
        rm -rf dist/ build/ *.egg-info/
    
    - name: Force set version to 0.1.3
      run: |
        # Update version in pyproject.toml
        sed -i 's/version = "0.1.2"/version = "0.1.3"/g' pyproject.toml
        # Also update any __version__ in Python files
        find . -name "*.py" -type f -exec sed -i 's/__version__ = "0.1.2"/__version__ = "0.1.3"/g' {} \;
        # Show the changes
        echo "Updated pyproject.toml version:"
        grep "version" pyproject.toml
    
    - name: Build package
      run: python -m build
    
    - name: Debug package files
      run: |
        echo "Built distribution files:"
        ls -la dist/
    
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        attestations: true
        skip-existing: true
